import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { z } from 'zod';

import {
  actionCatalogSchema,
  adapterStatusSchema,
  companionDialogueRunCreateRequestSchema,
  companionDialogueRunSchema,
  companionDialogueRunStatusRequestSchema,
  companionGuideDeliverySchema,
  companionGuideRequestSchema,
  companionInitialPlanRunCreateRequestSchema,
  companionInitialPlanRunSchema,
  companionInitialPlanRunStatusRequestSchema,
  companionReplanRunCreateRequestSchema,
  companionReplanRunSchema,
  companionReplanRunStatusRequestSchema,
  companionHeartbeatRequestSchema,
  companionHeartbeatResponseSchema,
  companionSessionHelloRequestSchema,
  companionSessionHelloResponseSchema,
  companionStateReportSchema,
  evalExportBundleSchema,
  evalExportRequestSchema,
  guidePlanSchema,
  guidePlanDiffSchema,
  guideGoalPromptRequestSchema,
  guideGoalRequestAcknowledgementSchema,
  guideGoalRequestListSchema,
  guideGoalRequestSchema,
  guideProposalDecisionSchema,
  guideProposalSchema,
  guideProposalSubmissionSchema,
  guideReplanSubmissionSchema,
  guideRevisionBranchListRequestSchema,
  guideRevisionBranchListSchema,
  guideRevisionRequestSchema,
  guideRevisionThreadHistoryRequestSchema,
  guideRevisionThreadHistorySchema,
  humanEvalAdjudicationSchema,
  humanEvalAnnotationSchema,
  humanEvalComparisonReportSchema,
  humanEvalSuiteSchema,
  interactionCatalogSchema,
  planningContextSchema,
  planningBenchmarkCaseSchema,
  planningPromptContextSchema,
  planningPromptPacketSchema,
  planningPromptRequestSchema,
  planningProposalDraftSchema,
  planningQualityEvaluationRequestSchema,
  planningQualityReportSchema,
  procedureAuthoringPromptContextSchema,
  procedureAuthoringPromptPacketSchema,
  procedureAuthoringPromptRequestSchema,
  procedureAuthoringCandidateTreeSchema,
  procedureAuthoringGenerateRequestSchema,
  procedureAuthoringGenerationResultSchema,
  procedureAuthoringValidationRequestSchema,
  procedureAuthoringValidationResultSchema,
  procedureTutorialTranscriptImportRequestSchema,
  procedureTutorialTranscriptGenerateRequestSchema,
  procedureTutorialYoutubeImportRequestSchema,
  procedureTutorialYoutubeTrackListRequestSchema,
  procedureTutorialYoutubeTrackListResultSchema,
  procedureTutorialYoutubeTrackRecommendationRequestSchema,
  procedureTutorialYoutubeTrackRecommendationResultSchema,
  procedureAuthoringMaterializationRequestSchema,
  procedureAuthoringMaterializationResultSchema,
  procedureLeafReplayAttestationSchema,
  procedureLeafReplayBindingSchema,
  procedureLeafReplayCurrentStateRequestSchema,
  procedureLeafReplayCurrentStateRequestResultSchema,
  procedureLeafReplayCurrentStateStatusRequestSchema,
  procedureLeafReplayCurrentStateStatusResultSchema,
  procedureLeafReplayCurrentStateVerificationSchema,
  procedureLeafReplayFailureRecoveryAttestationSchema,
  procedureLeafReplayFailureRecoveryFinalizeRequestSchema,
  procedureLeafReplayFailureRecoveryFinalizeResultSchema,
  procedureLeafReplayFinalizeRequestSchema,
  procedureLeafReplayFinalizeResultSchema,
  procedureLeafReplayProposalRequestSchema,
  procedureLeafReplayProposalResultSchema,
  procedureTreeSchema,
  procedureCompilationRequestSchema,
  procedureCompilationResultSchema,
  procedureTreeGetRequestSchema,
  procedureTreeListRequestSchema,
  procedureTreeListResultSchema,
  procedureOperationSearchRequestSchema,
  procedureOperationSearchResultSchema,
  procedureTreeStoreRequestSchema,
  procedureTreeStoreResultSchema,
  storedProcedureTreeSchema,
  plannerGenerateRequestSchema,
  plannerGenerationErrorSchema,
  plannerGenerationResultSchema,
  plannerProviderDescriptorSchema,
  plannerProviderListSchema,
  plannerReplanDraftSchema,
  plannerReplanGenerateRequestSchema,
  plannerReplanGenerationResultSchema,
  providerEvalRunSchema,
  replanningPromptContextSchema,
  replanningPromptPacketSchema,
  replanningPromptRequestSchema,
} from '../src/index.js';

const outputDirectory = resolve(process.cwd(), '../../protocol/schemas/v1');
mkdirSync(outputDirectory, { recursive: true });
const checkOnly = process.argv.includes('--check');

const schemas = [
  [
    'companion-session-hello-request.schema.json',
    'https://operatingline.dev/schema/v1/companion-session-hello-request.json',
    companionSessionHelloRequestSchema,
  ],
  [
    'companion-session-hello-response.schema.json',
    'https://operatingline.dev/schema/v1/companion-session-hello-response.json',
    companionSessionHelloResponseSchema,
  ],
  [
    'companion-session-heartbeat-request.schema.json',
    'https://operatingline.dev/schema/v1/companion-session-heartbeat-request.json',
    companionHeartbeatRequestSchema,
  ],
  [
    'companion-session-heartbeat-response.schema.json',
    'https://operatingline.dev/schema/v1/companion-session-heartbeat-response.json',
    companionHeartbeatResponseSchema,
  ],
  [
    'companion-dialogue-run-create-request.schema.json',
    'https://operatingline.dev/schema/v1/companion-dialogue-run-create-request.json',
    companionDialogueRunCreateRequestSchema,
  ],
  [
    'companion-dialogue-run-status-request.schema.json',
    'https://operatingline.dev/schema/v1/companion-dialogue-run-status-request.json',
    companionDialogueRunStatusRequestSchema,
  ],
  [
    'companion-dialogue-run.schema.json',
    'https://operatingline.dev/schema/v1/companion-dialogue-run.json',
    companionDialogueRunSchema,
  ],
  [
    'guide-goal-request.schema.json',
    'https://operatingline.dev/schema/v1/guide-goal-request.json',
    guideGoalRequestSchema,
  ],
  [
    'guide-goal-request-acknowledgement.schema.json',
    'https://operatingline.dev/schema/v1/guide-goal-request-acknowledgement.json',
    guideGoalRequestAcknowledgementSchema,
  ],
  [
    'guide-goal-request-list.schema.json',
    'https://operatingline.dev/schema/v1/guide-goal-request-list.json',
    guideGoalRequestListSchema,
  ],
  [
    'guide-goal-prompt-request.schema.json',
    'https://operatingline.dev/schema/v1/guide-goal-prompt-request.json',
    guideGoalPromptRequestSchema,
  ],
  [
    'human-eval-suite.schema.json',
    'https://operatingline.dev/schema/v1/human-eval-suite.json',
    humanEvalSuiteSchema,
  ],
  [
    'provider-eval-run.schema.json',
    'https://operatingline.dev/schema/v1/provider-eval-run.json',
    providerEvalRunSchema,
  ],
  [
    'human-eval-annotation.schema.json',
    'https://operatingline.dev/schema/v1/human-eval-annotation.json',
    humanEvalAnnotationSchema,
  ],
  [
    'human-eval-adjudication.schema.json',
    'https://operatingline.dev/schema/v1/human-eval-adjudication.json',
    humanEvalAdjudicationSchema,
  ],
  [
    'human-eval-comparison-report.schema.json',
    'https://operatingline.dev/schema/v1/human-eval-comparison-report.json',
    humanEvalComparisonReportSchema,
  ],
  [
    'companion-initial-plan-run-create-request.schema.json',
    'https://operatingline.dev/schema/v1/companion-initial-plan-run-create-request.json',
    companionInitialPlanRunCreateRequestSchema,
  ],
  [
    'companion-initial-plan-run-status-request.schema.json',
    'https://operatingline.dev/schema/v1/companion-initial-plan-run-status-request.json',
    companionInitialPlanRunStatusRequestSchema,
  ],
  [
    'companion-initial-plan-run.schema.json',
    'https://operatingline.dev/schema/v1/companion-initial-plan-run.json',
    companionInitialPlanRunSchema,
  ],
  [
    'companion-replan-run-create-request.schema.json',
    'https://operatingline.dev/schema/v1/companion-replan-run-create-request.json',
    companionReplanRunCreateRequestSchema,
  ],
  [
    'companion-replan-run-status-request.schema.json',
    'https://operatingline.dev/schema/v1/companion-replan-run-status-request.json',
    companionReplanRunStatusRequestSchema,
  ],
  [
    'companion-replan-run.schema.json',
    'https://operatingline.dev/schema/v1/companion-replan-run.json',
    companionReplanRunSchema,
  ],
  [
    'planner-provider-descriptor.schema.json',
    'https://operatingline.dev/schema/v1/planner-provider-descriptor.json',
    plannerProviderDescriptorSchema,
  ],
  [
    'planner-provider-list.schema.json',
    'https://operatingline.dev/schema/v1/planner-provider-list.json',
    plannerProviderListSchema,
  ],
  [
    'planner-generate-request.schema.json',
    'https://operatingline.dev/schema/v1/planner-generate-request.json',
    plannerGenerateRequestSchema,
  ],
  [
    'planner-generation-result.schema.json',
    'https://operatingline.dev/schema/v1/planner-generation-result.json',
    plannerGenerationResultSchema,
  ],
  [
    'planner-generation-error.schema.json',
    'https://operatingline.dev/schema/v1/planner-generation-error.json',
    plannerGenerationErrorSchema,
  ],
  [
    'planning-prompt-context.schema.json',
    'https://operatingline.dev/schema/v1/planning-prompt-context.json',
    planningPromptContextSchema,
  ],
  [
    'planning-prompt-request.schema.json',
    'https://operatingline.dev/schema/v1/planning-prompt-request.json',
    planningPromptRequestSchema,
  ],
  [
    'planning-prompt-packet.schema.json',
    'https://operatingline.dev/schema/v1/planning-prompt-packet.json',
    planningPromptPacketSchema,
  ],
  [
    'planning-proposal-draft.schema.json',
    'https://operatingline.dev/schema/v1/planning-proposal-draft.json',
    planningProposalDraftSchema,
  ],
  [
    'replanning-prompt-context.schema.json',
    'https://operatingline.dev/schema/v1/replanning-prompt-context.json',
    replanningPromptContextSchema,
  ],
  [
    'replanning-prompt-request.schema.json',
    'https://operatingline.dev/schema/v1/replanning-prompt-request.json',
    replanningPromptRequestSchema,
  ],
  [
    'replanning-prompt-packet.schema.json',
    'https://operatingline.dev/schema/v1/replanning-prompt-packet.json',
    replanningPromptPacketSchema,
  ],
  [
    'planner-replan-draft.schema.json',
    'https://operatingline.dev/schema/v1/planner-replan-draft.json',
    plannerReplanDraftSchema,
  ],
  [
    'planner-replan-generate-request.schema.json',
    'https://operatingline.dev/schema/v1/planner-replan-generate-request.json',
    plannerReplanGenerateRequestSchema,
  ],
  [
    'planner-replan-generation-result.schema.json',
    'https://operatingline.dev/schema/v1/planner-replan-generation-result.json',
    plannerReplanGenerationResultSchema,
  ],
  [
    'planning-benchmark-case.schema.json',
    'https://operatingline.dev/schema/v1/planning-benchmark-case.json',
    planningBenchmarkCaseSchema,
  ],
  [
    'planning-quality-evaluation-request.schema.json',
    'https://operatingline.dev/schema/v1/planning-quality-evaluation-request.json',
    planningQualityEvaluationRequestSchema,
  ],
  [
    'planning-quality-report.schema.json',
    'https://operatingline.dev/schema/v1/planning-quality-report.json',
    planningQualityReportSchema,
  ],
  [
    'guide-revision-thread-history-request.schema.json',
    'https://operatingline.dev/schema/v1/guide-revision-thread-history-request.json',
    guideRevisionThreadHistoryRequestSchema,
  ],
  [
    'guide-revision-thread-history.schema.json',
    'https://operatingline.dev/schema/v1/guide-revision-thread-history.json',
    guideRevisionThreadHistorySchema,
  ],
  [
    'guide-revision-branch-list-request.schema.json',
    'https://operatingline.dev/schema/v1/guide-revision-branch-list-request.json',
    guideRevisionBranchListRequestSchema,
  ],
  [
    'guide-revision-branch-list.schema.json',
    'https://operatingline.dev/schema/v1/guide-revision-branch-list.json',
    guideRevisionBranchListSchema,
  ],
  [
    'guide-plan-diff.schema.json',
    'https://operatingline.dev/schema/v1/guide-plan-diff.json',
    guidePlanDiffSchema,
  ],
  [
    'eval-export-request.schema.json',
    'https://operatingline.dev/schema/v1/eval-export-request.json',
    evalExportRequestSchema,
  ],
  [
    'eval-export-bundle.schema.json',
    'https://operatingline.dev/schema/v1/eval-export-bundle.json',
    evalExportBundleSchema,
  ],
  [
    'action-catalog.schema.json',
    'https://operatingline.dev/schema/v1/action-catalog.json',
    actionCatalogSchema,
  ],
  [
    'interaction-catalog.schema.json',
    'https://operatingline.dev/schema/v1/interaction-catalog.json',
    interactionCatalogSchema,
  ],
  [
    'procedure-tree.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree.json',
    procedureTreeSchema,
  ],
  [
    'procedure-authoring-candidate-tree.schema.json',
    'https://operatingline.dev/schema/v1/procedure-authoring-candidate-tree.json',
    procedureAuthoringCandidateTreeSchema,
  ],
  [
    'procedure-authoring-prompt-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-authoring-prompt-request.json',
    procedureAuthoringPromptRequestSchema,
  ],
  [
    'procedure-authoring-prompt-context.schema.json',
    'https://operatingline.dev/schema/v1/procedure-authoring-prompt-context.json',
    procedureAuthoringPromptContextSchema,
  ],
  [
    'procedure-authoring-prompt-packet.schema.json',
    'https://operatingline.dev/schema/v1/procedure-authoring-prompt-packet.json',
    procedureAuthoringPromptPacketSchema,
  ],
  [
    'procedure-authoring-validation-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-authoring-validation-request.json',
    procedureAuthoringValidationRequestSchema,
  ],
  [
    'procedure-authoring-validation-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-authoring-validation-result.json',
    procedureAuthoringValidationResultSchema,
  ],
  [
    'procedure-authoring-generate-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-authoring-generate-request.json',
    procedureAuthoringGenerateRequestSchema,
  ],
  [
    'procedure-authoring-generation-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-authoring-generation-result.json',
    procedureAuthoringGenerationResultSchema,
  ],
  [
    'procedure-tutorial-transcript-import-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-transcript-import-request.json',
    procedureTutorialTranscriptImportRequestSchema,
  ],
  [
    'procedure-tutorial-transcript-generate-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-transcript-generate-request.json',
    procedureTutorialTranscriptGenerateRequestSchema,
  ],
  [
    'procedure-tutorial-youtube-import-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-youtube-import-request.json',
    procedureTutorialYoutubeImportRequestSchema,
  ],
  [
    'procedure-tutorial-youtube-track-list-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-youtube-track-list-request.json',
    procedureTutorialYoutubeTrackListRequestSchema,
  ],
  [
    'procedure-tutorial-youtube-track-list-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-youtube-track-list-result.json',
    procedureTutorialYoutubeTrackListResultSchema,
  ],
  [
    'procedure-tutorial-youtube-track-recommendation-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-youtube-track-recommendation-request.json',
    procedureTutorialYoutubeTrackRecommendationRequestSchema,
  ],
  [
    'procedure-tutorial-youtube-track-recommendation-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-youtube-track-recommendation-result.json',
    procedureTutorialYoutubeTrackRecommendationResultSchema,
  ],
  [
    'procedure-authoring-materialization-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-authoring-materialization-request.json',
    procedureAuthoringMaterializationRequestSchema,
  ],
  [
    'procedure-authoring-materialization-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-authoring-materialization-result.json',
    procedureAuthoringMaterializationResultSchema,
  ],
  [
    'procedure-leaf-replay-proposal-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-proposal-request.json',
    procedureLeafReplayProposalRequestSchema,
  ],
  [
    'procedure-leaf-replay-binding.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-binding.json',
    procedureLeafReplayBindingSchema,
  ],
  [
    'procedure-leaf-replay-proposal-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-proposal-result.json',
    procedureLeafReplayProposalResultSchema,
  ],
  [
    'procedure-leaf-replay-finalize-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-finalize-request.json',
    procedureLeafReplayFinalizeRequestSchema,
  ],
  [
    'procedure-leaf-replay-attestation.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-attestation.json',
    procedureLeafReplayAttestationSchema,
  ],
  [
    'procedure-leaf-replay-finalize-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-finalize-result.json',
    procedureLeafReplayFinalizeResultSchema,
  ],
  [
    'procedure-leaf-replay-failure-recovery-finalize-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-failure-recovery-finalize-request.json',
    procedureLeafReplayFailureRecoveryFinalizeRequestSchema,
  ],
  [
    'procedure-leaf-replay-failure-recovery-attestation.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-failure-recovery-attestation.json',
    procedureLeafReplayFailureRecoveryAttestationSchema,
  ],
  [
    'procedure-leaf-replay-failure-recovery-finalize-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-failure-recovery-finalize-result.json',
    procedureLeafReplayFailureRecoveryFinalizeResultSchema,
  ],
  [
    'procedure-leaf-replay-current-state-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-current-state-request.json',
    procedureLeafReplayCurrentStateRequestSchema,
  ],
  [
    'procedure-leaf-replay-current-state-request-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-current-state-request-result.json',
    procedureLeafReplayCurrentStateRequestResultSchema,
  ],
  [
    'procedure-leaf-replay-current-state-status-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-current-state-status-request.json',
    procedureLeafReplayCurrentStateStatusRequestSchema,
  ],
  [
    'procedure-leaf-replay-current-state-verification.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-current-state-verification.json',
    procedureLeafReplayCurrentStateVerificationSchema,
  ],
  [
    'procedure-leaf-replay-current-state-status-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-current-state-status-result.json',
    procedureLeafReplayCurrentStateStatusResultSchema,
  ],
  [
    'procedure-compilation-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-compilation-request.json',
    procedureCompilationRequestSchema,
  ],
  [
    'procedure-compilation-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-compilation-result.json',
    procedureCompilationResultSchema,
  ],
  [
    'procedure-tree-store-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-store-request.json',
    procedureTreeStoreRequestSchema,
  ],
  [
    'procedure-tree-store-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-store-result.json',
    procedureTreeStoreResultSchema,
  ],
  [
    'procedure-tree-get-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-get-request.json',
    procedureTreeGetRequestSchema,
  ],
  [
    'stored-procedure-tree.schema.json',
    'https://operatingline.dev/schema/v1/stored-procedure-tree.json',
    storedProcedureTreeSchema,
  ],
  [
    'procedure-tree-list-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-list-request.json',
    procedureTreeListRequestSchema,
  ],
  [
    'procedure-tree-list-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-list-result.json',
    procedureTreeListResultSchema,
  ],
  [
    'procedure-operation-search-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-operation-search-request.json',
    procedureOperationSearchRequestSchema,
  ],
  [
    'procedure-operation-search-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-operation-search-result.json',
    procedureOperationSearchResultSchema,
  ],
  [
    'planning-context.schema.json',
    'https://operatingline.dev/schema/v1/planning-context.json',
    planningContextSchema,
  ],
  [
    'guide-revision-request.schema.json',
    'https://operatingline.dev/schema/v1/guide-revision-request.json',
    guideRevisionRequestSchema,
  ],
  [
    'guide-replan-submission.schema.json',
    'https://operatingline.dev/schema/v1/guide-replan-submission.json',
    guideReplanSubmissionSchema,
  ],
  [
    'guide-plan.schema.json',
    'https://operatingline.dev/schema/v1/guide-plan.json',
    guidePlanSchema,
  ],
  [
    'adapter-status.schema.json',
    'https://operatingline.dev/schema/v1/adapter-status.json',
    adapterStatusSchema,
  ],
  [
    'guide-proposal-submission.schema.json',
    'https://operatingline.dev/schema/v1/guide-proposal-submission.json',
    guideProposalSubmissionSchema,
  ],
  [
    'guide-proposal.schema.json',
    'https://operatingline.dev/schema/v1/guide-proposal.json',
    guideProposalSchema,
  ],
  [
    'guide-proposal-decision.schema.json',
    'https://operatingline.dev/schema/v1/guide-proposal-decision.json',
    guideProposalDecisionSchema,
  ],
  [
    'companion-guide-request.schema.json',
    'https://operatingline.dev/schema/v1/companion-guide-request.json',
    companionGuideRequestSchema,
  ],
  [
    'companion-guide-delivery.schema.json',
    'https://operatingline.dev/schema/v1/companion-guide-delivery.json',
    companionGuideDeliverySchema,
  ],
  [
    'companion-state-report.schema.json',
    'https://operatingline.dev/schema/v1/companion-state-report.json',
    companionStateReportSchema,
  ],
] as const;

for (const [filename, id, schema] of schemas) {
  const jsonSchema = z.toJSONSchema(schema, { target: 'draft-2020-12' });
  const outputPath = resolve(outputDirectory, filename);
  const expected = `${JSON.stringify({ ...jsonSchema, $id: id }, null, 2)}\n`;
  if (checkOnly) {
    const actual = readFileSync(outputPath, 'utf8');
    if (actual !== expected) {
      throw new Error(`${filename} is stale; run pnpm schema:generate`);
    }
  } else {
    writeFileSync(outputPath, expected);
  }
}
