import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { z } from 'zod';

import {
  actionCatalogSchema,
  adapterStatusSchema,
  companionActionExecutionCreateRequestSchema,
  companionActionExecutionDeliverySchema,
  companionActionExecutionResultSchema,
  companionActionExecutionStatusRequestSchema,
  companionActionExecutionStatusSchema,
  companionActionPollDeliverySchema,
  companionActionPollRequestSchema,
  companionActionResultAckSchema,
  companionDialogueRunCreateRequestSchema,
  companionDialogueRunSchema,
  companionDialogueRunStatusRequestSchema,
  companionGuideDeliverySchema,
  companionGuideRequestSchema,
  companionInitialPlanRunCreateRequestSchema,
  companionInitialPlanRunSchema,
  companionInitialPlanRunStatusRequestSchema,
  companionReplanRunCreateRequestSchema,
  companionReplanRunSchema,
  companionReplanRunStatusRequestSchema,
  companionHeartbeatRequestSchema,
  companionHeartbeatResponseSchema,
  companionSessionHelloRequestSchema,
  companionSessionHelloResponseSchema,
  companionStateReportSchema,
  evalExportBundleSchema,
  evalExportRequestSchema,
  guidePlanSchema,
  guidePlanDiffSchema,
  guideGoalPromptRequestSchema,
  guideGoalRequestAcknowledgementSchema,
  guideGoalRequestListSchema,
  guideGoalRequestSchema,
  guideProposalDecisionSchema,
  guideProposalSchema,
  guideProposalSubmissionSchema,
  guideReplanSubmissionSchema,
  guideRevisionBranchListRequestSchema,
  guideRevisionBranchListSchema,
  guideRevisionRequestSchema,
  guideRevisionThreadHistoryRequestSchema,
  guideRevisionThreadHistorySchema,
  humanEvalAdjudicationSchema,
  humanEvalAnnotationSchema,
  humanEvalComparisonReportSchema,
  humanEvalSuiteSchema,
  interactionCatalogSchema,
  planningContextSchema,
  planningBenchmarkCaseSchema,
  planningPromptContextSchema,
  planningPromptPacketSchema,
  planningPromptRequestSchema,
  planningProposalDraftSchema,
  planningQualityEvaluationRequestSchema,
  planningQualityReportSchema,
  procedureAuthoringPromptContextSchema,
  procedureAuthoringPromptPacketSchema,
  procedureAuthoringPromptRequestSchema,
  procedureAuthoringCandidateTreeSchema,
  procedureAuthoringGenerateRequestSchema,
  procedureAuthoringGenerationResultSchema,
  procedureAuthoringValidationRequestSchema,
  procedureAuthoringValidationResultSchema,
  procedureTutorialTranscriptImportRequestSchema,
  procedureTutorialTranscriptGenerateRequestSchema,
  procedureTutorialYoutubeImportRequestSchema,
  procedureTutorialAuthoringBindingSchema,
  procedureTutorialAuthoringResultSchema,
  procedureTutorialAuthoringReviewRequestSchema,
  procedureTutorialAuthoringResumeRequestSchema,
  procedureTutorialAuthoringRunCreateRequestSchema,
  procedureTutorialAuthoringRunStatusRequestSchema,
  procedureTutorialAuthoringRunStatusSchema,
  procedureTutorialMediaAnalysisRequestSchema,
  procedureTutorialMediaAnalysisResultSchema,
  procedureTutorialMediaCapabilitiesSchema,
  procedureTutorialMediaJobStatusSchema,
  procedureTutorialMediaJobStatusRequestSchema,
  procedureTutorialMediaResumeRequestSchema,
  procedureTutorialYoutubeTrackListRequestSchema,
  procedureTutorialYoutubeTrackListResultSchema,
  procedureTutorialYoutubeTrackRecommendationRequestSchema,
  procedureTutorialYoutubeTrackRecommendationResultSchema,
  procedureTutorialYoutubeTrackSelectionRequestSchema,
  procedureTutorialYoutubeTrackSelectionResultSchema,
  procedureAuthoringMaterializationRequestSchema,
  procedureAuthoringMaterializationResultSchema,
  procedureLeafReplayAttestationSchema,
  procedureLeafReplayBindingSchema,
  procedureLeafReplayCurrentStateRequestSchema,
  procedureLeafReplayCurrentStateRequestResultSchema,
  procedureLeafReplayCurrentStateStatusRequestSchema,
  procedureLeafReplayCurrentStateStatusResultSchema,
  procedureLeafReplayCurrentStateVerificationSchema,
  procedureLeafReplayFailureRecoveryAttestationSchema,
  procedureLeafReplayFailureRecoveryFinalizeRequestSchema,
  procedureLeafReplayFailureRecoveryFinalizeResultSchema,
  procedureLeafReplayFinalizeRequestSchema,
  procedureLeafReplayFinalizeResultSchema,
  procedureLeafReplayProposalRequestSchema,
  procedureLeafReplayProposalResultSchema,
  procedureTreeSchema,
  procedureCompilationRequestSchema,
  procedureCompilationResultSchema,
  procedureTreeGetRequestSchema,
  procedureTreeListRequestSchema,
  procedureTreeListResultSchema,
  procedureOperationSearchRequestSchema,
  procedureOperationSearchResultSchema,
  procedureSemanticRetrievalCompletedEventSchema,
  procedureSemanticRetrievalFailedEventSchema,
  procedureSemanticRetrievalProviderDisclosureListSchema,
  procedureSemanticRetrievalProviderRuntimeOutputAttestationSchema,
  procedureSemanticRetrievalProviderRuntimeTreatmentAttestationSchema,
  procedureSemanticRetrievalRequestSchema,
  procedureSemanticRetrievalRequestedEventSchema,
  procedureSemanticRetrievalResultSchema,
  procedureRefinementCreateRequestSchema,
  procedureRefinementDialogueCompletedEventSchema,
  procedureRefinementDialogueFailedEventSchema,
  procedureRefinementDialoguePromptPacketSchema,
  procedureRefinementDialogueProviderResultSchema,
  procedureRefinementDialogueRequestedEventSchema,
  procedureRefinementGenerationCompletedEventSchema,
  procedureRefinementGenerationFailedEventSchema,
  procedureRefinementGenerationOutcomeSchema,
  procedureRefinementGenerationRequestedEventSchema,
  procedureRefinementLocalityReportSchema,
  procedureRefinementPromptPacketSchema,
  procedureRefinementProviderDisclosureListSchema,
  procedureRefinementProviderInputPolicySchema,
  procedureRefinementProviderResultSchema,
  procedureRefinementProviderRuntimeTreatmentAttestationSchema,
  procedureRefinementReviewRequestSchema,
  procedureRefinementReviewedEventSchema,
  procedureRefinementRunStatusRequestSchema,
  procedureRefinementRunStatusSchema,
  procedureRefinementSemanticContextBindingSchema,
  procedureRefinementSemanticContextReceiptRequestSchema,
  procedureRefinementScopeSchema,
  procedureTreeStoreRequestSchema,
  procedureTreeStoreResultSchema,
  procedureTreeEditorBranchCreateRequestSchema,
  procedureTreeEditorBranchCreateResultSchema,
  procedureTreeEditorBranchGetRequestSchema,
  procedureTreeEditorBranchGetResultSchema,
  procedureTreeEditorBranchListRequestSchema,
  procedureTreeEditorBranchListResultSchema,
  procedureTreeEditorWorkspaceRequestSchema,
  procedureTreeEditorWorkspaceResultSchema,
  procedureTreeEditorDiffResultSchema,
  procedureTreeEditorEditPreviewRequestSchema,
  procedureTreeEditorEditPreviewResultSchema,
  procedureTreeEditorMergePreviewRequestSchema,
  procedureTreeEditorMergePreviewResultSchema,
  procedureTreeEditorCommitRequestSchema,
  procedureTreeEditorCommitResultSchema,
  procedureTreeEditorRevisionCommitSchema,
  procedureTreeEditorBranchHistoryRequestSchema,
  procedureTreeEditorBranchHistoryResultSchema,
  procedureTreeEditorCommentCreateRequestSchema,
  procedureTreeEditorCommentCreateResultSchema,
  procedureTreeEditorCommentListRequestSchema,
  procedureTreeEditorCommentListResultSchema,
  procedureTreeEditorParameterFormRequestSchema,
  procedureTreeEditorParameterFormResultSchema,
  storedProcedureTreeSchema,
  plannerGenerateRequestSchema,
  plannerGenerationErrorSchema,
  plannerGenerationResultSchema,
  plannerProviderDescriptorSchema,
  plannerProviderListSchema,
  plannerReplanDraftSchema,
  plannerReplanGenerateRequestSchema,
  plannerReplanGenerationResultSchema,
  providerEvalRunSchema,
  replanningPromptContextSchema,
  replanningPromptPacketSchema,
  replanningPromptRequestSchema,
} from '../src/index.js';

const outputDirectory = resolve(process.cwd(), '../../protocol/schemas/v1');
mkdirSync(outputDirectory, { recursive: true });
const checkOnly = process.argv.includes('--check');

const schemas = [
  [
    'companion-action-execution-create-request.schema.json',
    'https://operatingline.dev/schema/v1/companion-action-execution-create-request.json',
    companionActionExecutionCreateRequestSchema,
  ],
  [
    'companion-action-execution-delivery.schema.json',
    'https://operatingline.dev/schema/v1/companion-action-execution-delivery.json',
    companionActionExecutionDeliverySchema,
  ],
  [
    'companion-action-execution-result.schema.json',
    'https://operatingline.dev/schema/v1/companion-action-execution-result.json',
    companionActionExecutionResultSchema,
  ],
  [
    'companion-action-execution-status-request.schema.json',
    'https://operatingline.dev/schema/v1/companion-action-execution-status-request.json',
    companionActionExecutionStatusRequestSchema,
  ],
  [
    'companion-action-execution-status.schema.json',
    'https://operatingline.dev/schema/v1/companion-action-execution-status.json',
    companionActionExecutionStatusSchema,
  ],
  [
    'companion-action-poll-request.schema.json',
    'https://operatingline.dev/schema/v1/companion-action-poll-request.json',
    companionActionPollRequestSchema,
  ],
  [
    'companion-action-poll-delivery.schema.json',
    'https://operatingline.dev/schema/v1/companion-action-poll-delivery.json',
    companionActionPollDeliverySchema,
  ],
  [
    'companion-action-result-ack.schema.json',
    'https://operatingline.dev/schema/v1/companion-action-result-ack.json',
    companionActionResultAckSchema,
  ],
  [
    'procedure-tree-editor-branch-create-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-branch-create-request.json',
    procedureTreeEditorBranchCreateRequestSchema,
  ],
  [
    'procedure-tree-editor-branch-create-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-branch-create-result.json',
    procedureTreeEditorBranchCreateResultSchema,
  ],
  [
    'procedure-tree-editor-branch-get-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-branch-get-request.json',
    procedureTreeEditorBranchGetRequestSchema,
  ],
  [
    'procedure-tree-editor-branch-get-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-branch-get-result.json',
    procedureTreeEditorBranchGetResultSchema,
  ],
  [
    'procedure-tree-editor-branch-list-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-branch-list-request.json',
    procedureTreeEditorBranchListRequestSchema,
  ],
  [
    'procedure-tree-editor-branch-list-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-branch-list-result.json',
    procedureTreeEditorBranchListResultSchema,
  ],
  [
    'procedure-tree-editor-workspace-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-workspace-request.json',
    procedureTreeEditorWorkspaceRequestSchema,
  ],
  [
    'procedure-tree-editor-workspace-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-workspace-result.json',
    procedureTreeEditorWorkspaceResultSchema,
  ],
  [
    'procedure-tree-editor-diff-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-diff-result.json',
    procedureTreeEditorDiffResultSchema,
  ],
  [
    'procedure-tree-editor-edit-preview-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-edit-preview-request.json',
    procedureTreeEditorEditPreviewRequestSchema,
  ],
  [
    'procedure-tree-editor-edit-preview-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-edit-preview-result.json',
    procedureTreeEditorEditPreviewResultSchema,
  ],
  [
    'procedure-tree-editor-merge-preview-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-merge-preview-request.json',
    procedureTreeEditorMergePreviewRequestSchema,
  ],
  [
    'procedure-tree-editor-merge-preview-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-merge-preview-result.json',
    procedureTreeEditorMergePreviewResultSchema,
  ],
  [
    'procedure-tree-editor-commit-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-commit-request.json',
    procedureTreeEditorCommitRequestSchema,
  ],
  [
    'procedure-tree-editor-commit-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-commit-result.json',
    procedureTreeEditorCommitResultSchema,
  ],
  [
    'procedure-tree-editor-revision-commit.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-revision-commit.json',
    procedureTreeEditorRevisionCommitSchema,
  ],
  [
    'procedure-tree-editor-branch-history-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-branch-history-request.json',
    procedureTreeEditorBranchHistoryRequestSchema,
  ],
  [
    'procedure-tree-editor-branch-history-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-branch-history-result.json',
    procedureTreeEditorBranchHistoryResultSchema,
  ],
  [
    'procedure-tree-editor-comment-create-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-comment-create-request.json',
    procedureTreeEditorCommentCreateRequestSchema,
  ],
  [
    'procedure-tree-editor-comment-create-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-comment-create-result.json',
    procedureTreeEditorCommentCreateResultSchema,
  ],
  [
    'procedure-tree-editor-comment-list-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-comment-list-request.json',
    procedureTreeEditorCommentListRequestSchema,
  ],
  [
    'procedure-tree-editor-comment-list-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-comment-list-result.json',
    procedureTreeEditorCommentListResultSchema,
  ],
  [
    'procedure-tree-editor-parameter-form-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-parameter-form-request.json',
    procedureTreeEditorParameterFormRequestSchema,
  ],
  [
    'procedure-tree-editor-parameter-form-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-editor-parameter-form-result.json',
    procedureTreeEditorParameterFormResultSchema,
  ],
  [
    'companion-session-hello-request.schema.json',
    'https://operatingline.dev/schema/v1/companion-session-hello-request.json',
    companionSessionHelloRequestSchema,
  ],
  [
    'companion-session-hello-response.schema.json',
    'https://operatingline.dev/schema/v1/companion-session-hello-response.json',
    companionSessionHelloResponseSchema,
  ],
  [
    'companion-session-heartbeat-request.schema.json',
    'https://operatingline.dev/schema/v1/companion-session-heartbeat-request.json',
    companionHeartbeatRequestSchema,
  ],
  [
    'companion-session-heartbeat-response.schema.json',
    'https://operatingline.dev/schema/v1/companion-session-heartbeat-response.json',
    companionHeartbeatResponseSchema,
  ],
  [
    'companion-dialogue-run-create-request.schema.json',
    'https://operatingline.dev/schema/v1/companion-dialogue-run-create-request.json',
    companionDialogueRunCreateRequestSchema,
  ],
  [
    'companion-dialogue-run-status-request.schema.json',
    'https://operatingline.dev/schema/v1/companion-dialogue-run-status-request.json',
    companionDialogueRunStatusRequestSchema,
  ],
  [
    'companion-dialogue-run.schema.json',
    'https://operatingline.dev/schema/v1/companion-dialogue-run.json',
    companionDialogueRunSchema,
  ],
  [
    'guide-goal-request.schema.json',
    'https://operatingline.dev/schema/v1/guide-goal-request.json',
    guideGoalRequestSchema,
  ],
  [
    'guide-goal-request-acknowledgement.schema.json',
    'https://operatingline.dev/schema/v1/guide-goal-request-acknowledgement.json',
    guideGoalRequestAcknowledgementSchema,
  ],
  [
    'guide-goal-request-list.schema.json',
    'https://operatingline.dev/schema/v1/guide-goal-request-list.json',
    guideGoalRequestListSchema,
  ],
  [
    'guide-goal-prompt-request.schema.json',
    'https://operatingline.dev/schema/v1/guide-goal-prompt-request.json',
    guideGoalPromptRequestSchema,
  ],
  [
    'human-eval-suite.schema.json',
    'https://operatingline.dev/schema/v1/human-eval-suite.json',
    humanEvalSuiteSchema,
  ],
  [
    'provider-eval-run.schema.json',
    'https://operatingline.dev/schema/v1/provider-eval-run.json',
    providerEvalRunSchema,
  ],
  [
    'human-eval-annotation.schema.json',
    'https://operatingline.dev/schema/v1/human-eval-annotation.json',
    humanEvalAnnotationSchema,
  ],
  [
    'human-eval-adjudication.schema.json',
    'https://operatingline.dev/schema/v1/human-eval-adjudication.json',
    humanEvalAdjudicationSchema,
  ],
  [
    'human-eval-comparison-report.schema.json',
    'https://operatingline.dev/schema/v1/human-eval-comparison-report.json',
    humanEvalComparisonReportSchema,
  ],
  [
    'companion-initial-plan-run-create-request.schema.json',
    'https://operatingline.dev/schema/v1/companion-initial-plan-run-create-request.json',
    companionInitialPlanRunCreateRequestSchema,
  ],
  [
    'companion-initial-plan-run-status-request.schema.json',
    'https://operatingline.dev/schema/v1/companion-initial-plan-run-status-request.json',
    companionInitialPlanRunStatusRequestSchema,
  ],
  [
    'companion-initial-plan-run.schema.json',
    'https://operatingline.dev/schema/v1/companion-initial-plan-run.json',
    companionInitialPlanRunSchema,
  ],
  [
    'companion-replan-run-create-request.schema.json',
    'https://operatingline.dev/schema/v1/companion-replan-run-create-request.json',
    companionReplanRunCreateRequestSchema,
  ],
  [
    'companion-replan-run-status-request.schema.json',
    'https://operatingline.dev/schema/v1/companion-replan-run-status-request.json',
    companionReplanRunStatusRequestSchema,
  ],
  [
    'companion-replan-run.schema.json',
    'https://operatingline.dev/schema/v1/companion-replan-run.json',
    companionReplanRunSchema,
  ],
  [
    'planner-provider-descriptor.schema.json',
    'https://operatingline.dev/schema/v1/planner-provider-descriptor.json',
    plannerProviderDescriptorSchema,
  ],
  [
    'planner-provider-list.schema.json',
    'https://operatingline.dev/schema/v1/planner-provider-list.json',
    plannerProviderListSchema,
  ],
  [
    'planner-generate-request.schema.json',
    'https://operatingline.dev/schema/v1/planner-generate-request.json',
    plannerGenerateRequestSchema,
  ],
  [
    'planner-generation-result.schema.json',
    'https://operatingline.dev/schema/v1/planner-generation-result.json',
    plannerGenerationResultSchema,
  ],
  [
    'planner-generation-error.schema.json',
    'https://operatingline.dev/schema/v1/planner-generation-error.json',
    plannerGenerationErrorSchema,
  ],
  [
    'planning-prompt-context.schema.json',
    'https://operatingline.dev/schema/v1/planning-prompt-context.json',
    planningPromptContextSchema,
  ],
  [
    'planning-prompt-request.schema.json',
    'https://operatingline.dev/schema/v1/planning-prompt-request.json',
    planningPromptRequestSchema,
  ],
  [
    'planning-prompt-packet.schema.json',
    'https://operatingline.dev/schema/v1/planning-prompt-packet.json',
    planningPromptPacketSchema,
  ],
  [
    'planning-proposal-draft.schema.json',
    'https://operatingline.dev/schema/v1/planning-proposal-draft.json',
    planningProposalDraftSchema,
  ],
  [
    'replanning-prompt-context.schema.json',
    'https://operatingline.dev/schema/v1/replanning-prompt-context.json',
    replanningPromptContextSchema,
  ],
  [
    'replanning-prompt-request.schema.json',
    'https://operatingline.dev/schema/v1/replanning-prompt-request.json',
    replanningPromptRequestSchema,
  ],
  [
    'replanning-prompt-packet.schema.json',
    'https://operatingline.dev/schema/v1/replanning-prompt-packet.json',
    replanningPromptPacketSchema,
  ],
  [
    'planner-replan-draft.schema.json',
    'https://operatingline.dev/schema/v1/planner-replan-draft.json',
    plannerReplanDraftSchema,
  ],
  [
    'planner-replan-generate-request.schema.json',
    'https://operatingline.dev/schema/v1/planner-replan-generate-request.json',
    plannerReplanGenerateRequestSchema,
  ],
  [
    'planner-replan-generation-result.schema.json',
    'https://operatingline.dev/schema/v1/planner-replan-generation-result.json',
    plannerReplanGenerationResultSchema,
  ],
  [
    'planning-benchmark-case.schema.json',
    'https://operatingline.dev/schema/v1/planning-benchmark-case.json',
    planningBenchmarkCaseSchema,
  ],
  [
    'planning-quality-evaluation-request.schema.json',
    'https://operatingline.dev/schema/v1/planning-quality-evaluation-request.json',
    planningQualityEvaluationRequestSchema,
  ],
  [
    'planning-quality-report.schema.json',
    'https://operatingline.dev/schema/v1/planning-quality-report.json',
    planningQualityReportSchema,
  ],
  [
    'guide-revision-thread-history-request.schema.json',
    'https://operatingline.dev/schema/v1/guide-revision-thread-history-request.json',
    guideRevisionThreadHistoryRequestSchema,
  ],
  [
    'guide-revision-thread-history.schema.json',
    'https://operatingline.dev/schema/v1/guide-revision-thread-history.json',
    guideRevisionThreadHistorySchema,
  ],
  [
    'guide-revision-branch-list-request.schema.json',
    'https://operatingline.dev/schema/v1/guide-revision-branch-list-request.json',
    guideRevisionBranchListRequestSchema,
  ],
  [
    'guide-revision-branch-list.schema.json',
    'https://operatingline.dev/schema/v1/guide-revision-branch-list.json',
    guideRevisionBranchListSchema,
  ],
  [
    'guide-plan-diff.schema.json',
    'https://operatingline.dev/schema/v1/guide-plan-diff.json',
    guidePlanDiffSchema,
  ],
  [
    'eval-export-request.schema.json',
    'https://operatingline.dev/schema/v1/eval-export-request.json',
    evalExportRequestSchema,
  ],
  [
    'eval-export-bundle.schema.json',
    'https://operatingline.dev/schema/v1/eval-export-bundle.json',
    evalExportBundleSchema,
  ],
  [
    'action-catalog.schema.json',
    'https://operatingline.dev/schema/v1/action-catalog.json',
    actionCatalogSchema,
  ],
  [
    'interaction-catalog.schema.json',
    'https://operatingline.dev/schema/v1/interaction-catalog.json',
    interactionCatalogSchema,
  ],
  [
    'procedure-tree.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree.json',
    procedureTreeSchema,
  ],
  [
    'procedure-authoring-candidate-tree.schema.json',
    'https://operatingline.dev/schema/v1/procedure-authoring-candidate-tree.json',
    procedureAuthoringCandidateTreeSchema,
  ],
  [
    'procedure-authoring-prompt-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-authoring-prompt-request.json',
    procedureAuthoringPromptRequestSchema,
  ],
  [
    'procedure-authoring-prompt-context.schema.json',
    'https://operatingline.dev/schema/v1/procedure-authoring-prompt-context.json',
    procedureAuthoringPromptContextSchema,
  ],
  [
    'procedure-authoring-prompt-packet.schema.json',
    'https://operatingline.dev/schema/v1/procedure-authoring-prompt-packet.json',
    procedureAuthoringPromptPacketSchema,
  ],
  [
    'procedure-authoring-validation-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-authoring-validation-request.json',
    procedureAuthoringValidationRequestSchema,
  ],
  [
    'procedure-authoring-validation-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-authoring-validation-result.json',
    procedureAuthoringValidationResultSchema,
  ],
  [
    'procedure-authoring-generate-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-authoring-generate-request.json',
    procedureAuthoringGenerateRequestSchema,
  ],
  [
    'procedure-authoring-generation-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-authoring-generation-result.json',
    procedureAuthoringGenerationResultSchema,
  ],
  [
    'procedure-tutorial-transcript-import-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-transcript-import-request.json',
    procedureTutorialTranscriptImportRequestSchema,
  ],
  [
    'procedure-tutorial-transcript-generate-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-transcript-generate-request.json',
    procedureTutorialTranscriptGenerateRequestSchema,
  ],
  [
    'procedure-tutorial-youtube-import-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-youtube-import-request.json',
    procedureTutorialYoutubeImportRequestSchema,
  ],
  [
    'procedure-tutorial-authoring-run-create-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-authoring-run-create-request.json',
    procedureTutorialAuthoringRunCreateRequestSchema,
  ],
  [
    'procedure-tutorial-authoring-run-status-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-authoring-run-status-request.json',
    procedureTutorialAuthoringRunStatusRequestSchema,
  ],
  [
    'procedure-tutorial-authoring-run-status.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-authoring-run-status.json',
    procedureTutorialAuthoringRunStatusSchema,
  ],
  [
    'procedure-tutorial-authoring-review-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-authoring-review-request.json',
    procedureTutorialAuthoringReviewRequestSchema,
  ],
  [
    'procedure-tutorial-authoring-resume-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-authoring-resume-request.json',
    procedureTutorialAuthoringResumeRequestSchema,
  ],
  [
    'procedure-tutorial-authoring-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-authoring-result.json',
    procedureTutorialAuthoringResultSchema,
  ],
  [
    'procedure-tutorial-authoring-binding.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-authoring-binding.json',
    procedureTutorialAuthoringBindingSchema,
  ],
  [
    'procedure-tutorial-media-analysis-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-media-analysis-request.json',
    procedureTutorialMediaAnalysisRequestSchema,
  ],
  [
    'procedure-tutorial-media-analysis-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-media-analysis-result.json',
    procedureTutorialMediaAnalysisResultSchema,
  ],
  [
    'procedure-tutorial-media-job-status.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-media-job-status.json',
    procedureTutorialMediaJobStatusSchema,
  ],
  [
    'procedure-tutorial-media-job-status-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-media-job-status-request.json',
    procedureTutorialMediaJobStatusRequestSchema,
  ],
  [
    'procedure-tutorial-media-resume-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-media-resume-request.json',
    procedureTutorialMediaResumeRequestSchema,
  ],
  [
    'procedure-tutorial-media-capabilities.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-media-capabilities.json',
    procedureTutorialMediaCapabilitiesSchema,
  ],
  [
    'procedure-tutorial-youtube-track-list-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-youtube-track-list-request.json',
    procedureTutorialYoutubeTrackListRequestSchema,
  ],
  [
    'procedure-tutorial-youtube-track-list-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-youtube-track-list-result.json',
    procedureTutorialYoutubeTrackListResultSchema,
  ],
  [
    'procedure-tutorial-youtube-track-recommendation-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-youtube-track-recommendation-request.json',
    procedureTutorialYoutubeTrackRecommendationRequestSchema,
  ],
  [
    'procedure-tutorial-youtube-track-recommendation-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-youtube-track-recommendation-result.json',
    procedureTutorialYoutubeTrackRecommendationResultSchema,
  ],
  [
    'procedure-tutorial-youtube-track-selection-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-youtube-track-selection-request.json',
    procedureTutorialYoutubeTrackSelectionRequestSchema,
  ],
  [
    'procedure-tutorial-youtube-track-selection-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tutorial-youtube-track-selection-result.json',
    procedureTutorialYoutubeTrackSelectionResultSchema,
  ],
  [
    'procedure-authoring-materialization-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-authoring-materialization-request.json',
    procedureAuthoringMaterializationRequestSchema,
  ],
  [
    'procedure-authoring-materialization-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-authoring-materialization-result.json',
    procedureAuthoringMaterializationResultSchema,
  ],
  [
    'procedure-leaf-replay-proposal-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-proposal-request.json',
    procedureLeafReplayProposalRequestSchema,
  ],
  [
    'procedure-leaf-replay-binding.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-binding.json',
    procedureLeafReplayBindingSchema,
  ],
  [
    'procedure-leaf-replay-proposal-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-proposal-result.json',
    procedureLeafReplayProposalResultSchema,
  ],
  [
    'procedure-leaf-replay-finalize-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-finalize-request.json',
    procedureLeafReplayFinalizeRequestSchema,
  ],
  [
    'procedure-leaf-replay-attestation.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-attestation.json',
    procedureLeafReplayAttestationSchema,
  ],
  [
    'procedure-leaf-replay-finalize-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-finalize-result.json',
    procedureLeafReplayFinalizeResultSchema,
  ],
  [
    'procedure-leaf-replay-failure-recovery-finalize-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-failure-recovery-finalize-request.json',
    procedureLeafReplayFailureRecoveryFinalizeRequestSchema,
  ],
  [
    'procedure-leaf-replay-failure-recovery-attestation.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-failure-recovery-attestation.json',
    procedureLeafReplayFailureRecoveryAttestationSchema,
  ],
  [
    'procedure-leaf-replay-failure-recovery-finalize-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-failure-recovery-finalize-result.json',
    procedureLeafReplayFailureRecoveryFinalizeResultSchema,
  ],
  [
    'procedure-leaf-replay-current-state-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-current-state-request.json',
    procedureLeafReplayCurrentStateRequestSchema,
  ],
  [
    'procedure-leaf-replay-current-state-request-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-current-state-request-result.json',
    procedureLeafReplayCurrentStateRequestResultSchema,
  ],
  [
    'procedure-leaf-replay-current-state-status-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-current-state-status-request.json',
    procedureLeafReplayCurrentStateStatusRequestSchema,
  ],
  [
    'procedure-leaf-replay-current-state-verification.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-current-state-verification.json',
    procedureLeafReplayCurrentStateVerificationSchema,
  ],
  [
    'procedure-leaf-replay-current-state-status-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-leaf-replay-current-state-status-result.json',
    procedureLeafReplayCurrentStateStatusResultSchema,
  ],
  [
    'procedure-compilation-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-compilation-request.json',
    procedureCompilationRequestSchema,
  ],
  [
    'procedure-compilation-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-compilation-result.json',
    procedureCompilationResultSchema,
  ],
  [
    'procedure-tree-store-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-store-request.json',
    procedureTreeStoreRequestSchema,
  ],
  [
    'procedure-tree-store-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-store-result.json',
    procedureTreeStoreResultSchema,
  ],
  [
    'procedure-tree-get-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-get-request.json',
    procedureTreeGetRequestSchema,
  ],
  [
    'stored-procedure-tree.schema.json',
    'https://operatingline.dev/schema/v1/stored-procedure-tree.json',
    storedProcedureTreeSchema,
  ],
  [
    'procedure-tree-list-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-list-request.json',
    procedureTreeListRequestSchema,
  ],
  [
    'procedure-tree-list-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-tree-list-result.json',
    procedureTreeListResultSchema,
  ],
  [
    'procedure-operation-search-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-operation-search-request.json',
    procedureOperationSearchRequestSchema,
  ],
  [
    'procedure-operation-search-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-operation-search-result.json',
    procedureOperationSearchResultSchema,
  ],
  [
    'procedure-semantic-retrieval-provider-disclosure-list.schema.json',
    'https://operatingline.dev/schema/v1/procedure-semantic-retrieval-provider-disclosure-list.json',
    procedureSemanticRetrievalProviderDisclosureListSchema,
  ],
  [
    'procedure-semantic-retrieval-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-semantic-retrieval-request.json',
    procedureSemanticRetrievalRequestSchema,
  ],
  [
    'procedure-semantic-retrieval-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-semantic-retrieval-result.json',
    procedureSemanticRetrievalResultSchema,
  ],
  [
    'procedure-semantic-retrieval-requested-event.schema.json',
    'https://operatingline.dev/schema/v1/procedure-semantic-retrieval-requested-event.json',
    procedureSemanticRetrievalRequestedEventSchema,
  ],
  [
    'procedure-semantic-retrieval-completed-event.schema.json',
    'https://operatingline.dev/schema/v1/procedure-semantic-retrieval-completed-event.json',
    procedureSemanticRetrievalCompletedEventSchema,
  ],
  [
    'procedure-semantic-retrieval-failed-event.schema.json',
    'https://operatingline.dev/schema/v1/procedure-semantic-retrieval-failed-event.json',
    procedureSemanticRetrievalFailedEventSchema,
  ],
  [
    'procedure-semantic-retrieval-provider-runtime-treatment-attestation.schema.json',
    'https://operatingline.dev/schema/v1/procedure-semantic-retrieval-provider-runtime-treatment-attestation.json',
    procedureSemanticRetrievalProviderRuntimeTreatmentAttestationSchema,
  ],
  [
    'procedure-semantic-retrieval-provider-runtime-output-attestation.schema.json',
    'https://operatingline.dev/schema/v1/procedure-semantic-retrieval-provider-runtime-output-attestation.json',
    procedureSemanticRetrievalProviderRuntimeOutputAttestationSchema,
  ],
  [
    'procedure-refinement-provider-disclosure-list.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-provider-disclosure-list.json',
    procedureRefinementProviderDisclosureListSchema,
  ],
  [
    'procedure-refinement-provider-input-policy.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-provider-input-policy.json',
    procedureRefinementProviderInputPolicySchema,
  ],
  [
    'procedure-refinement-provider-runtime-treatment-attestation.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-provider-runtime-treatment-attestation.json',
    procedureRefinementProviderRuntimeTreatmentAttestationSchema,
  ],
  [
    'procedure-refinement-create-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-create-request.json',
    procedureRefinementCreateRequestSchema,
  ],
  [
    'procedure-refinement-semantic-context-receipt-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-semantic-context-receipt-request.json',
    procedureRefinementSemanticContextReceiptRequestSchema,
  ],
  [
    'procedure-refinement-semantic-context-receipt.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-semantic-context-receipt.json',
    procedureRefinementSemanticContextBindingSchema,
  ],
  [
    'procedure-refinement-scope.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-scope.json',
    procedureRefinementScopeSchema,
  ],
  [
    'procedure-refinement-locality-report.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-locality-report.json',
    procedureRefinementLocalityReportSchema,
  ],
  [
    'procedure-refinement-dialogue-prompt-packet.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-dialogue-prompt-packet.json',
    procedureRefinementDialoguePromptPacketSchema,
  ],
  [
    'procedure-refinement-dialogue-provider-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-dialogue-provider-result.json',
    procedureRefinementDialogueProviderResultSchema,
  ],
  [
    'procedure-refinement-dialogue-requested-event.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-dialogue-requested-event.json',
    procedureRefinementDialogueRequestedEventSchema,
  ],
  [
    'procedure-refinement-dialogue-completed-event.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-dialogue-completed-event.json',
    procedureRefinementDialogueCompletedEventSchema,
  ],
  [
    'procedure-refinement-dialogue-failed-event.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-dialogue-failed-event.json',
    procedureRefinementDialogueFailedEventSchema,
  ],
  [
    'procedure-refinement-prompt-packet.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-prompt-packet.json',
    procedureRefinementPromptPacketSchema,
  ],
  [
    'procedure-refinement-provider-result.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-provider-result.json',
    procedureRefinementProviderResultSchema,
  ],
  [
    'procedure-refinement-generation-outcome.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-generation-outcome.json',
    procedureRefinementGenerationOutcomeSchema,
  ],
  [
    'procedure-refinement-generation-requested-event.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-generation-requested-event.json',
    procedureRefinementGenerationRequestedEventSchema,
  ],
  [
    'procedure-refinement-generation-completed-event.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-generation-completed-event.json',
    procedureRefinementGenerationCompletedEventSchema,
  ],
  [
    'procedure-refinement-generation-failed-event.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-generation-failed-event.json',
    procedureRefinementGenerationFailedEventSchema,
  ],
  [
    'procedure-refinement-review-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-review-request.json',
    procedureRefinementReviewRequestSchema,
  ],
  [
    'procedure-refinement-reviewed-event.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-reviewed-event.json',
    procedureRefinementReviewedEventSchema,
  ],
  [
    'procedure-refinement-run-status-request.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-run-status-request.json',
    procedureRefinementRunStatusRequestSchema,
  ],
  [
    'procedure-refinement-run-status.schema.json',
    'https://operatingline.dev/schema/v1/procedure-refinement-run-status.json',
    procedureRefinementRunStatusSchema,
  ],
  [
    'planning-context.schema.json',
    'https://operatingline.dev/schema/v1/planning-context.json',
    planningContextSchema,
  ],
  [
    'guide-revision-request.schema.json',
    'https://operatingline.dev/schema/v1/guide-revision-request.json',
    guideRevisionRequestSchema,
  ],
  [
    'guide-replan-submission.schema.json',
    'https://operatingline.dev/schema/v1/guide-replan-submission.json',
    guideReplanSubmissionSchema,
  ],
  [
    'guide-plan.schema.json',
    'https://operatingline.dev/schema/v1/guide-plan.json',
    guidePlanSchema,
  ],
  [
    'adapter-status.schema.json',
    'https://operatingline.dev/schema/v1/adapter-status.json',
    adapterStatusSchema,
  ],
  [
    'guide-proposal-submission.schema.json',
    'https://operatingline.dev/schema/v1/guide-proposal-submission.json',
    guideProposalSubmissionSchema,
  ],
  [
    'guide-proposal.schema.json',
    'https://operatingline.dev/schema/v1/guide-proposal.json',
    guideProposalSchema,
  ],
  [
    'guide-proposal-decision.schema.json',
    'https://operatingline.dev/schema/v1/guide-proposal-decision.json',
    guideProposalDecisionSchema,
  ],
  [
    'companion-guide-request.schema.json',
    'https://operatingline.dev/schema/v1/companion-guide-request.json',
    companionGuideRequestSchema,
  ],
  [
    'companion-guide-delivery.schema.json',
    'https://operatingline.dev/schema/v1/companion-guide-delivery.json',
    companionGuideDeliverySchema,
  ],
  [
    'companion-state-report.schema.json',
    'https://operatingline.dev/schema/v1/companion-state-report.json',
    companionStateReportSchema,
  ],
] as const;

function hardenDraft7Tuples(value: unknown): void {
  if (Array.isArray(value)) {
    for (const item of value) hardenDraft7Tuples(item);
    return;
  }
  if (value === null || typeof value !== 'object') return;
  const record = value as Record<string, unknown>;
  if (Array.isArray(record['items'])) {
    const length = record['items'].length;
    if (length === 0) {
      record['items'] = {};
      delete record['additionalItems'];
    } else {
      record['additionalItems'] = false;
    }
    record['minItems'] = length;
    record['maxItems'] = length;
  }
  for (const nested of Object.values(record)) hardenDraft7Tuples(nested);
}

function hardenProcedureTreeMergeResolutions(value: unknown): void {
  if (value === null || typeof value !== 'object') return;
  const record = value as Record<string, unknown>;
  const properties = record['properties'];
  if (properties !== null && typeof properties === 'object') {
    const propertyRecord = properties as Record<string, unknown>;
    const choice = propertyRecord['choice'];
    if (
      propertyRecord['conflict'] !== undefined &&
      propertyRecord['custom'] !== undefined &&
      choice !== null &&
      typeof choice === 'object' &&
      Array.isArray((choice as Record<string, unknown>)['enum']) &&
      ((choice as Record<string, unknown>)['enum'] as unknown[]).includes('custom')
    ) {
      record['allOf'] = [
        {
          if: { properties: { choice: { const: 'custom' } }, required: ['choice'] },
          then: { required: ['custom'] },
          else: { not: { required: ['custom'] } },
        },
      ];
    }
  }
  for (const nested of Object.values(record)) hardenProcedureTreeMergeResolutions(nested);
}

function hardenProcedureTreeEditorSchema(filename: string, schema: Record<string, unknown>): void {
  hardenProcedureTreeMergeResolutions(schema);
  if (filename === 'procedure-tree-editor-parameter-form-result.schema.json') {
    schema['$comment'] =
      'Field minimum, maximum, pattern, and length members are sibling metadata for the editor UI. Generic JSON Schema validators cannot enforce every metadata-to-value dependency; the runtime Zod contract is authoritative for those relationships.';
  }
  if (filename === 'procedure-tree-editor-commit-request.schema.json') {
    schema['allOf'] = [
      {
        if: { properties: { operation: { const: 'edit' } }, required: ['operation'] },
        then: {
          properties: {
            previewBinding: {
              properties: { operation: { const: 'edit' } },
              required: ['operation'],
            },
          },
        },
      },
      {
        if: { properties: { operation: { const: 'merge' } }, required: ['operation'] },
        then: {
          properties: {
            previewBinding: {
              properties: { operation: { const: 'merge' } },
              required: ['operation'],
            },
          },
        },
      },
    ];
  }
  if (filename === 'procedure-tree-editor-revision-commit.schema.json') {
    schema['allOf'] = [
      {
        if: { properties: { operation: { const: 'edit' } }, required: ['operation'] },
        then: {
          properties: { source: { type: 'null' }, mergeBase: { type: 'null' } },
        },
      },
      {
        if: { properties: { operation: { const: 'merge' } }, required: ['operation'] },
        then: {
          properties: {
            source: { type: 'object' },
            mergeBase: { type: 'object' },
          },
        },
      },
    ];
  }
}

for (const [filename, id, schema] of schemas) {
  const draft7TupleSchema =
    filename.startsWith('procedure-tutorial-media-') ||
    filename.startsWith('procedure-tutorial-authoring-');
  const jsonSchema = z.toJSONSchema(schema, {
    target: draft7TupleSchema ? 'draft-7' : 'draft-2020-12',
  });
  if (draft7TupleSchema) hardenDraft7Tuples(jsonSchema);
  hardenProcedureTreeEditorSchema(filename, jsonSchema);
  const outputPath = resolve(outputDirectory, filename);
  const expected = `${JSON.stringify({ ...jsonSchema, $id: id }, null, 2)}\n`;
  if (checkOnly) {
    const actual = readFileSync(outputPath, 'utf8');
    if (actual !== expected) {
      throw new Error(`${filename} is stale; run pnpm schema:generate`);
    }
  } else {
    writeFileSync(outputPath, expected);
  }
}
