"""Blender-facing infrastructure implementations."""

from .blender_actions import (
    action_registry,
    build_resource_registry,
    find_artifact,
    forget_managed_collection,
    resolve_receipt_anchor,
    resolve_resource,
)
from .companion_transport import CompanionTransport, validate_companion_url
from .native_history import (
    NativeHistoryRestore,
    cancel_native_history,
    commit_native_history,
    discard_native_history,
    native_history_error,
    native_undo_checkpoint_attestation,
    prepare_native_history,
    prepared_native_history_changed,
    register_native_history,
    unregister_native_history,
)
from .overlay import disable_overlay, enable_overlay, overlay_enabled
from .scene_preparation import remove_factory_startup_objects
from .shortcut_history import (
    ShortcutHistoryTransition,
    acknowledge_shortcut_transition_recovery,
    acknowledge_shortcut_transition_results,
    arm_failed_shortcut_history,
    arm_shortcut_history,
    lock_shortcut_history_indeterminate,
    reconcile_shortcut_terminal_outbox,
    reconcile_shortcut_transition_outbox,
    rebind_shortcut_history,
    register_shortcut_history,
    shortcut_history_current_attestation,
    shortcut_history_error,
    shortcut_history_has_transition_outbox,
    shortcut_history_mutation_locked,
    shortcut_history_transition_checkpoint,
    unregister_shortcut_history,
)

__all__ = (
    "action_registry",
    "acknowledge_shortcut_transition_results",
    "acknowledge_shortcut_transition_recovery",
    "arm_failed_shortcut_history",
    "arm_shortcut_history",
    "build_resource_registry",
    "cancel_native_history",
    "commit_native_history",
    "CompanionTransport",
    "disable_overlay",
    "enable_overlay",
    "overlay_enabled",
    "forget_managed_collection",
    "find_artifact",
    "discard_native_history",
    "native_history_error",
    "native_undo_checkpoint_attestation",
    "NativeHistoryRestore",
    "lock_shortcut_history_indeterminate",
    "prepare_native_history",
    "prepared_native_history_changed",
    "register_native_history",
    "register_shortcut_history",
    "reconcile_shortcut_terminal_outbox",
    "reconcile_shortcut_transition_outbox",
    "rebind_shortcut_history",
    "remove_factory_startup_objects",
    "resolve_receipt_anchor",
    "resolve_resource",
    "shortcut_history_current_attestation",
    "shortcut_history_error",
    "shortcut_history_has_transition_outbox",
    "shortcut_history_mutation_locked",
    "shortcut_history_transition_checkpoint",
    "ShortcutHistoryTransition",
    "unregister_native_history",
    "unregister_shortcut_history",
    "validate_companion_url",
)
